import KratosMultiphysics
import KratosMultiphysics.ExternalSolversApplication
import KratosMultiphysics.DelaunayMeshingApplication
import KratosMultiphysics.SolversApplication
import KratosMultiphysics.PfemApplication
import KratosMultiphysics.ConstitutiveModelsApplication
import KratosMultiphysics.SolidMechanicsApplication
import KratosMultiphysics.FluidDynamicsApplication

import MainPfem

MainPfem.PfemSolution(KratosMultiphysics.Model()).Run()
